# Generated by Django 6.0.3 on 2026-03-27 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_sent', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='Kullanıcının kendisini tanıttığı kısa biyografi.', null=True)),
                ('city', models.CharField(blank=True, help_text='Yaşadığı şehir', max_length=100, null=True)),
                ('mbti_type', models.CharField(blank=True, max_length=4, null=True)),
                ('budget_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoommatePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('private', 'Private Room'), ('shared', 'Shared Room')], default='private', max_length=10)),
                ('max_roommates', models.IntegerField(default=1)),
                ('cleanliness_level', models.IntegerField(default=3)),
                ('cleaning_frequency', models.IntegerField(default=1, help_text='Haftalık temizlik sıklığı')),
                ('cooks_often', models.BooleanField(default=False)),
                ('dietary_preference', models.CharField(choices=[('none', 'Belirtilmemiş'), ('omnivore', 'Hepçil (Her şeyi yer)'), ('vegetarian', 'Vejetaryen'), ('vegan', 'Vegan'), ('pescatarian', 'Pesketaryen')], default='none', max_length=20)),
                ('has_pet', models.BooleanField(default=False)),
                ('pet_tolerance', models.BooleanField(default=True, help_text='Evde evcil hayvan kabul ediyor mu?')),
                ('allergic_to_pets', models.BooleanField(default=False)),
                ('guest_frequency', models.IntegerField(default=2, help_text='Haftalık misafir sıklığı')),
                ('party_tolerance', models.IntegerField(default=3)),
                ('noise_tolerance', models.IntegerField(default=3)),
                ('budget_flexibility', models.IntegerField(default=3)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('working_hours', models.CharField(blank=True, max_length=100, null=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='core.profile')),
            ],
        ),
        migrations.CreateModel(
            name='UserPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='profile_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_verified', models.BooleanField(default=False)),
                ('id_verified', models.BooleanField(default=False)),
                ('has_criminal_record', models.BooleanField(default=False, help_text='Resmi sabıka kaydı beyanı')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('user_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_user1', to=settings.AUTH_USER_MODEL)),
                ('user_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_user2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user_1', 'user_2')},
            },
        ),
    ]
