# Generated by Django 6.0.4 on 2026-04-28 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='negotiation',
            name='user1_choices',
        ),
        migrations.RemoveField(
            model_name='negotiation',
            name='user1_ready',
        ),
        migrations.RemoveField(
            model_name='negotiation',
            name='user2_choices',
        ),
        migrations.RemoveField(
            model_name='negotiation',
            name='user2_ready',
        ),
        migrations.AddField(
            model_name='negotiation',
            name='current_offer',
            field=models.JSONField(blank=True, default=dict, verbose_name='Masadaki Güncel Teklif'),
        ),
        migrations.AddField(
            model_name='negotiation',
            name='current_turn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_turns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='negotiation',
            name='round_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='negotiation',
            name='status',
            field=models.CharField(choices=[('ONGOING', 'Pazarlık Devam Ediyor'), ('ACCEPTED', 'Sözleşme İmzalandı'), ('REJECTED', 'Masa Devrildi')], default='ONGOING', max_length=15),
        ),
        migrations.AddField(
            model_name='negotiation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
