# Generated by Django 6.0.3 on 2026-04-01 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AlterField(
            model_name='roommatepreference',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='accounts.profile'),
        ),
        migrations.RemoveField(
            model_name='verification',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserPhoto',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Verification',
        ),
    ]
