# Generated by Django 6.0.4 on 2026-05-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_negotiation_user1_choices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='negotiation',
            name='user1_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='negotiation',
            name='user2_ready',
            field=models.BooleanField(default=False),
        ),
    ]
