# Generated by Django 6.0.4 on 2026-05-01 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_negotiation_user1_ready_negotiation_user2_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='negotiation',
            name='user1_choices',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='negotiation',
            name='user2_choices',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
