# Generated by Django 6.0.4 on 2026-05-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_negotiation_user1_choices_negotiation_user2_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='negotiation',
            name='user1_koz',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='negotiation',
            name='user2_koz',
            field=models.IntegerField(default=2),
        ),
    ]
