# Generated by Django 6.0.4 on 2026-04-15 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500, null=True, verbose_name='Hakkımda')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Doğum Tarihi')),
                ('gender', models.CharField(choices=[('male', 'Erkek'), ('female', 'Kadın'), ('other', 'Diğer'), ('prefer_not_to_say', 'Belirtmek İstemiyorum')], default='prefer_not_to_say', max_length=20, verbose_name='Cinsiyet')),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Yaşadığı Şehir')),
                ('mbti_type', models.CharField(blank=True, max_length=4, null=True, verbose_name='MBTI Tipi')),
                ('budget_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Bütçe Limiti')),
                ('diet_preference', models.CharField(choices=[('omnivore', 'Hepçil (🥩)'), ('vegetarian', 'Vejetaryen (🥦)'), ('vegan', 'Vegan (🌱)')], default='omnivore', max_length=20, verbose_name='Diyet Tercihi')),
                ('last_seen', models.DateTimeField(blank=True, null=True, verbose_name='Son Görülme')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_onboarded', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='profile_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_verified', models.BooleanField(default=False)),
                ('id_verified', models.BooleanField(default=False)),
                ('has_criminal_record', models.BooleanField(default=False, help_text='Resmi sabıka kaydı beyanı')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
