# Generated by Django 6.0.4 on 2026-04-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_allergy',
            field=models.BooleanField(default=False, verbose_name='Alerjisi Var'),
        ),
        migrations.AddField(
            model_name='profile',
            name='has_pet',
            field=models.BooleanField(default=False, verbose_name='Evcil Hayvanı Var'),
        ),
    ]
