# Generated by Django 6.0.4 on 2026-04-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_has_allergy_profile_has_pet'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cleaning_frequency',
            field=models.CharField(choices=[('DAILY', 'Her gün'), ('WEEKLY', 'Haftada bir'), ('BIWEEKLY', 'İki haftada bir'), ('RELAXED', 'Kirlendikçe')], default='WEEKLY', max_length=20, verbose_name='Temizlik Sıklığı'),
        ),
        migrations.AddField(
            model_name='profile',
            name='guest_policy',
            field=models.CharField(choices=[('NO_GUESTS', 'Misafir kesinlikle yasak'), ('WEEKENDS', 'Sadece hafta sonları'), ('ANYTIME', 'Önceden haber vererek her zaman')], default='WEEKENDS', max_length=20, verbose_name='Misafir Politikası'),
        ),
        migrations.AddField(
            model_name='profile',
            name='pets_allowed',
            field=models.BooleanField(default=False, verbose_name='Evcil Hayvan Kabul Ediyor'),
        ),
        migrations.AddField(
            model_name='profile',
            name='sleep_schedule',
            field=models.CharField(choices=[('EARLY_BIRD', 'Erkenci (Gece 12 öncesi sessizlik)'), ('NIGHT_OWL', 'Gece Kuşu (Gece ses sorun olmaz)'), ('FLEXIBLE', 'Esnek (Uyku saatim değişir)')], default='FLEXIBLE', max_length=20, verbose_name='Uyku Düzeni'),
        ),
        migrations.AddField(
            model_name='profile',
            name='smoking_allowed',
            field=models.BooleanField(default=False, verbose_name='Evde Sigara İçilebilir'),
        ),
    ]
