# Generated by Django 6.0.4 on 2026-05-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_cleaning_frequency_profile_guest_policy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Kullanıcının hesabı doğrulanmış mı?'),
        ),
    ]
